entier	mot_clef	entier
$a	identificateur	$a
;	symbole	POINT_VIRGULE
main	identificateur	main
(	symbole	PARENTHESE_OUVRANTE
)	symbole	PARENTHESE_FERMANTE
{	symbole	ACCOLADE_OUVRANTE
$a	identificateur	$a
=	symbole	EGAL
5	nombre	5
;	symbole	POINT_VIRGULE
ecrire	mot_clef	ecrire
(	symbole	PARENTHESE_OUVRANTE
$a	identificateur	$a
)	symbole	PARENTHESE_FERMANTE
;	symbole	POINT_VIRGULE
}	symbole	ACCOLADE_FERMANTE
$extra	identificateur	$extra
=	symbole	EGAL
0	nombre	0
;	symbole	POINT_VIRGULE
